# Generated by Django 3.2.25 on 2024-06-17 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0004_auto_20240617_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grades',
            name='credit',
        ),
        migrations.AddField(
            model_name='courses',
            name='credit',
            field=models.IntegerField(default=2),
        ),
    ]
