# Generated by Django 3.2.25 on 2024-06-17 03:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0003_auto_20240616_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='grades',
            name='credit',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='grades',
            name='grade',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
