# Generated by Django 3.2.25 on 2024-06-17 03:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0005_auto_20240617_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='grades',
            name='four_points_scale',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
