# Generated by Django 5.0.3 on 2024-06-20 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0009_auto_20240618_0919'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grades',
        ),
    ]
